# Generated by Django 5.2.7 on 2025-11-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.local', unique=True)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsible')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(choices=[('temperature', 'Temperature'), ('luminosity', 'Luminosity'), ('humidity', 'Humidity'), ('accountant', 'Accountant')], max_length=20)),
                ('mac_address', models.CharField(max_length=12)),
                ('unity_mec', models.CharField(max_length=10)),
                ('latitude', models.FloatField(max_length=15)),
                ('longitude', models.FloatField(max_length=15)),
                ('status', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.environment')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
        ),
    ]
