# Generated by Django 5.2.7 on 2025-11-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(max_length=20),
        ),
    ]
