# Generated by Django 5.2.7 on 2025-11-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sensor_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.local'),
        ),
    ]
