# Generated by Django 5.2.7 on 2025-11-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_history_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='timestamp',
        ),
    ]
