# Generated by Django 5.2.7 on 2025-12-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_sensor_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
