# Generated by Django 5.2.7 on 2025-12-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_environment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='unity_mec',
            new_name='unity_med',
        ),
    ]
